### ISSUE TITLE
Can not autocomplete the paths within {%static ''%}

### ISSUE THREAD

**Issue by RabbitsRun** [almahdi404/code-django#10]
<img width="337" alt="截屏2023-08-24 上午12 31 55" src="https://github.com/almahdi404/code-django/assets/74236389/b3baa7c3-5de1-4b7c-a92c-947dacb6d146">
This extension would be perfect if this glitch handled

**Comment by almahdi404** [comment]
I am actually building a template engine for django which uses pure html syntax. It will be much better than the [DTL](https://docs.djangoproject.com/en/4.2/ref/templates/language/)

I will build full vscode support for it. So, I don't want to spent any time in building more features for **DTL**
