### ISSUE TITLE
(cmd+click)Can no longer jump files in html

### ISSUE THREAD

**Issue by jiayouzl** [almahdi404/code-django#8]
<img width="556" alt="iShot_2023-01-14_18 08 10" src="https://user-images.githubusercontent.com/7685337/212466827-ad8ba4e0-a5cb-44cb-a880-cb719fade685.png">
<img width="712" alt="image" src="https://user-images.githubusercontent.com/7685337/212466862-1174bfaa-4669-464b-81c4-baa05f1fda0e.png">

I can't jump to the file using cmd + click.

**Comment by almahdi404** [comment]
can you show the project folder structure?

**Comment by jiayouzl** [comment]
> where is the `head.html` located?

head.html and tpl.html in the same directory

**Comment by jiayouzl** [comment]
Clicking on the variable name passed by Python in html will not jump.

**Comment by almahdi404** [comment]
It's working properly in my system. Check if the extension is activated.

**Comment by jiayouzl** [comment]
> It's working properly in my system. Check if the extension is activated.

## Open state
<img width="316" alt="image" src="https://user-images.githubusercontent.com/7685337/212519953-44b85c7b-719e-44a2-91ea-b4e4ff2e0da6.png">

## my code
[DownUrl](https://filedoge.com/download/a302f9c56d5e6f2f35eafe657ca10d0a64ab24425b3e56cc29d0cf1d7c71a5afbbc3fbda1da442275f33)

**Comment by almahdi404** [comment]
It is not being activated.
It should be activated if the project contains a `manage.py` or `apps.py` file.



> ## my code
> 
> [DownUrl](https://1drv.ms/u/s!AtmF1AkoLz9Ajkd1aoSkLYziyQg2?e=RWM8VI)

and what's in it?

**Comment by jiayouzl** [comment]
> It is not being activated. It should be activated if the project contains a `manage.py` or `apps.py` file.
> 
> > ## my code
> > [DownUrl](https://1drv.ms/u/s!AtmF1AkoLz9Ajkd1aoSkLYziyQg2?e=RWM8VI)
> 
> and what's in it?

What you said is in it, and the plugin is also activated, but the html can't jump

**Comment by jiayouzl** [comment]
> Reference in n



> It is not being activated. It should be activated if the project contains a `manage.py` or `apps.py` file.
> 
> > ## my code
> > [DownUrl](https://1drv.ms/u/s!AtmF1AkoLz9Ajkd1aoSkLYziyQg2?e=RWM8VI)
> 
> and what's in it?

Inside is the Django code that I can't jump to. There are several files you mentioned, and the plugin is also started.

**Comment by almahdi404** [comment]
> <img alt="image" width="316" src="https://user-images.githubusercontent.com/7685337/212519953-44b85c7b-719e-44a2-91ea-b4e4ff2e0da6.png">

No. It's not being activated.
If it was activated, the activation time would be there on the right side.

**Comment by jiayouzl** [comment]
> > <img alt="image" width="316" src="https://user-images.githubusercontent.com/7685337/212519953-44b85c7b-719e-44a2-91ea-b4e4ff2e0da6.png">
> 
> No. It's not being activated. If it was activated, the activation time would be there on the right side.

<img width="612" alt="image" src="https://user-images.githubusercontent.com/7685337/212549586-d84ff583-c659-4607-8c70-9c948ea511d2.png">
Activated.... Not activated is grey.

**Comment by jiayouzl** [comment]
<img width="290" alt="image" src="https://user-images.githubusercontent.com/7685337/212549669-7ca695a2-14dd-4010-9947-9e15587a710b.png">
This is the inactive state

**Comment by jiayouzl** [comment]
![iShot_2023-01-15_23 28 43](https://user-images.githubusercontent.com/7685337/212550206-236843f0-7de0-4fb7-b368-2a84814af619.gif)

**Comment by jiayouzl** [comment]
![iShot_2023-01-15_23 31 53](https://user-images.githubusercontent.com/7685337/212550353-34831746-f9d7-4071-9caa-b562cc5b44dc.gif)
Code snippets are used normally

**Comment by almahdi404** [comment]
Snippets work without being activated.

Check the `Runtime Status`

![Screenshot from 2023-01-15 23-07-30](https://user-images.githubusercontent.com/68297852/212555773-36cc1f80-4c25-4132-852c-7cac6f85dd27.png)

**Comment by jiayouzl** [comment]
> Snippets work without being activated.
> 
> 
> 
> Check the `Runtime Status`
> 
> 
> 
> ![Screenshot from 2023-01-15 23-07-30](https://user-images.githubusercontent.com/68297852/212555773-36cc1f80-4c25-4132-852c-7cac6f85dd27.png)
> 
> 
> 
> 

I can't find where to activate. How to activate?

**Comment by almahdi404** [comment]
> I can't find where to activate. How to activate?thank you！

I am asking you to check if the extension is activated in the `Runtime Status` tab.

**Comment by jiayouzl** [comment]
> 



> > I can't find where to activate. How to activate?thank you！
> 
> I am asking you to check if the extension is activated in the `Runtime Status` tab.

<img width="1173" alt="image" src="https://user-images.githubusercontent.com/7685337/212587853-98fc2e1b-352b-4b64-9460-c799afdd1d4e.png">
<img width="917" alt="image" src="https://user-images.githubusercontent.com/7685337/212587884-89a07984-1bde-461a-8d97-2ce8de0d5b60.png">

Opening the entire project plugin does show an inactive state
