### ISSUE TITLE
0.5.2 in bugs

### ISSUE THREAD

**Issue by jiayouzl** [almahdi404/code-django#9]
Perception code will not be triggered without entering {{}}.
![iShot_2023-02-07_11 29 52](https://user-images.githubusercontent.com/7685337/217141416-dea1a402-d39c-4019-98e4-324626ca51a6.gif)

**Comment by jiayouzl** [comment]
Using {{}} can be perceived, but the code after carriage return conflicts.

**Comment by almahdi404** [comment]
It's a bug in vscode@1.75 https://github.com/microsoft/vscode/issues/173244 and will be fixed in  vscode@1.75.1
